# -*- coding: utf-8 -*-
"""Guion del vídeo de coipo_contrato2, en formato podcast a dos voces.

Catalina lleva el hilo; Lorenzo pregunta, objeta y trae analogías. La broma
interna aquí es que Lorenzo desconfía del papel —«el papel siempre gana»— y
vuelve al final.

CADA LATIDO ES UNA FRASE Y UN PLANO. El campo `foto` nombra una ESCENA de
escenas_contrato.jsx, no una captura: este vídeo no tiene interfaz que enseñar,
así que los planos son los arquetipos de composición.

El énfasis va con *asteriscos*: sirve igual para edge-tts (trocea la frase y da
prosodia a cada trozo) que para Qwen (lo pide por instrucción en lenguaje
natural).
"""

GUION = [
    # ------------------------------------------------------------- apertura
    dict(v='c', tono='vivo', foto='gancho', p=0.20,
         t="Un contrato sale de la oficina para ir a firma. ¿Cuánto lleva fuera?"),
    dict(v='l', tono='normal', foto='gancho', p=0.15,
         t="Pues… ni idea. Y eso ya es la respuesta, ¿no?"),
    dict(v='c', tono='vivo', foto='gancho', p=0.15,
         t="Ésa *es* la respuesta. Hasta hace poco nadie podía contestarla."),
    dict(v='l', tono='suave', foto='gancho', p=0.45,
         t="Empezamos fuerte hoy."),
    dict(v='c', tono='normal', foto='quees', p=0.20,
         rot="Sistema de Gestión de Contratos · CONAF",
         t="El Sistema de Gestión de Contratos de CONAF existe para responder justo esa pregunta."),
    dict(v='c', tono='normal', foto='quees', p=0.25,
         t="Administra *el ciclo de vida completo* del contrato físico de un funcionario."),
    dict(v='l', tono='vivo', foto='quees', p=0.15,
         t="Físico. O sea, papel de verdad."),
    dict(v='c', tono='normal', foto='quees', p=0.60,
         t="Papel de verdad. Y ahí está toda la gracia del asunto."),

    # -------------------------------------------------------- el problema
    dict(v='c', tono='normal', foto='papel', p=0.15,
         t="El papel tiene un problema que no tiene un archivo: *circula*."),
    dict(v='l', tono='normal', foto='papel', p=0.15,
         t="Se imprime, se lleva a firmar, cambia de manos…"),
    dict(v='c', tono='normal', foto='papel', p=0.20,
         t="…espera en un escritorio, y de pronto nadie sabe dónde está."),
    dict(v='l', tono='vivo', foto='papel', p=0.15,
         t="Yo siempre digo que *el papel siempre gana*."),
    dict(v='c', tono='vivo', foto='papel', p=0.30,
         t="Ya te veía venir con eso."),
    dict(v='l', tono='normal', foto='papel', p=0.15,
         t="¿Y la solución es digitalizarlo todo y olvidarse?"),
    dict(v='c', tono='lento', foto='remate1', p=0.20,
         rot="No elimina el papel. Le pone seguimiento.",
         t="No. Y eso es lo interesante: el sistema *no elimina el papel*."),
    dict(v='c', tono='normal', foto='remate1', p=0.15,
         t="Le pone seguimiento."),
    dict(v='l', tono='suave', foto='remate1', p=0.60,
         t="Eso me gusta más que la promesa de siempre. Es más honesto."),

    # ------------------------------------------------ la máquina de estados
    dict(v='c', tono='normal', foto='estados', p=0.20,
         rot="Cinco estados, y solo cinco",
         t="El corazón del sistema es una máquina de estados, y sólo tiene *cinco*."),
    dict(v='c', tono='normal', foto='estados', p=0.15,
         t="Pendiente, cuando aún no se revisa."),
    dict(v='c', tono='normal', foto='estados', p=0.15,
         t="Revisado, cuando alguien lo validó."),
    dict(v='c', tono='normal', foto='estados', p=0.15,
         t="Impreso, cuando ya existe en papel."),
    dict(v='c', tono='normal', foto='estados', p=0.15,
         t="Esperando firma, mientras está fuera de la oficina."),
    dict(v='c', tono='lento', foto='estados', p=0.20,
         t="Y completado, cuando *vuelve firmado*."),
    dict(v='l', tono='vivo', foto='estados', p=0.15,
         t="¿Y si alguien se salta uno? Porque se lo van a saltar."),
    dict(v='c', tono='vivo', foto='salto', p=0.20,
         t="No pueden. Y ahí está lo bien pensado."),
    dict(v='c', tono='lento', foto='salto', p=0.20,
         rot="Lo decide el servidor, no la interfaz",
         t="Si alguien lo intenta, el servidor responde con *un error de conflicto* y la transición no ocurre."),
    dict(v='l', tono='normal', foto='salto', p=0.15,
         t="O sea que no basta con ocultar el botón en la pantalla."),
    dict(v='c', tono='normal', foto='salto', p=0.20,
         t="Exacto. Lo decide *el servidor*, no la interfaz. Una pantalla se puede engañar."),
    dict(v='l', tono='suave', foto='salto', p=0.60,
         t="Tú siempre vas a mirar dónde está la decisión de verdad."),

    # ------------------------------------------------- plantillas y bandeja
    dict(v='c', tono='normal', foto='plantillas', p=0.15,
         t="Los documentos salen de plantillas registradas: indefinido, honorarios, y las demás modalidades."),
    dict(v='l', tono='vivo', foto='plantillas', p=0.15,
         t="Y cada modalidad pide datos distintos, imagino."),
    dict(v='c', tono='normal', foto='plantillas', p=0.20,
         rot="Campos en JSON, no columnas fijas",
         t="Sí, así que el formulario *se adapta*. Los campos viven en JSON, no en columnas fijas de la base."),
    dict(v='l', tono='normal', foto='plantillas', p=0.15,
         t="Traducido: añadir una modalidad no obliga a tocar la base de datos."),
    dict(v='c', tono='vivo', foto='plantillas', p=0.30,
         t="Traducido mucho mejor que yo, además."),
    dict(v='c', tono='normal', foto='plantillas', p=0.55,
         t="Y el pe de efe se abre *dentro* de la aplicación, no en una carpeta pública."),
    dict(v='c', tono='normal', foto='bandeja', p=0.15,
         rot="La bandeja, ordenada por estado",
         t="El trabajo del día a día se organiza en pestañas por estado."),
    dict(v='c', tono='normal', foto='bandeja', p=0.15,
         t="Funcionarios, con pe de efe, completados y pendientes."),
    dict(v='c', tono='normal', foto='bandeja', p=0.20,
         t="Cada persona abre un panel con su ficha y su flujo, sin salir de la lista."),
    dict(v='l', tono='normal', foto='bandeja', p=0.60,
         t="Así el encargado ve el punto exacto de cada caso *de un vistazo*."),

    # ------------------------------------------------------------ seguridad
    dict(v='c', tono='normal', foto='seguridad', p=0.15,
         t="Sobre seguridad hay una sola regla, y es tajante."),
    dict(v='c', tono='lento', foto='seguridad', p=0.20,
         rot="Ningún dato sensible se sirve estático",
         t="*Ningún dato sensible se sirve estático.*"),
    dict(v='l', tono='vivo', foto='seguridad', p=0.15,
         t="Explícame qué significa eso en cristiano."),
    dict(v='c', tono='normal', foto='seguridad', p=0.20,
         t="Que tener la dirección de un documento *no basta* para abrirlo."),
    dict(v='c', tono='normal', foto='seguridad', p=0.15,
         t="Hace falta un token válido, y de vida corta."),
    dict(v='l', tono='normal', foto='seguridad', p=0.60,
         t="Nada de pasarse un enlace por correo y que lo abra cualquiera."),

    # --------------------------------------------------------- la broma vuelve
    dict(v='l', tono='vivo', foto='infra', p=0.15,
         t="Vale. ¿Y cuánta máquina hace falta para vigilar papel?"),
    dict(v='c', tono='suave', foto='infra', p=0.25,
         t="Sabía que ibas a volver al papel."),
    dict(v='c', tono='lento', foto='infra', p=0.20,
         rot="32 procesadores en cuatro máquinas",
         t="*Treinta y dos procesadores*, noventa y seis gigas de memoria y dos teras de disco."),
    dict(v='c', tono='normal', foto='infra', p=0.15,
         t="Repartidos en cuatro máquinas."),
    dict(v='l', tono='vivo', foto='infra', p=0.15,
         t="¿Cuatro? ¿Y por qué no una?"),
    dict(v='c', tono='normal', foto='infra', p=0.20,
         t="Porque hacen cosas distintas: la base de datos, el backend, los trabajos que generan los documentos…"),
    dict(v='c', tono='normal', foto='infra', p=0.60,
         t="…y la puerta de entrada. Si generar un pe de efe pesado tumbara la web, sería un mal diseño."),

    # --------------------------------------------------------------- cierre
    dict(v='c', tono='normal', foto='cierre', p=0.20,
         t="Resumiendo: cinco estados que no se saltan, plantillas que se adaptan, y documentos que exigen permiso."),
    dict(v='l', tono='normal', foto='cierre', p=0.15,
         t="Y un contrato en papel que sigue siendo un contrato en papel."),
    dict(v='c', tono='lento', foto='cierre', p=0.20,
         rot="Ahora se sabe dónde está",
         t="Sigue siéndolo. La diferencia es que ahora, en cualquier momento, *se puede responder dónde está*."),
    dict(v='l', tono='vivo', foto='cierre', p=0.15,
         t="Entonces retiro lo que dije. El papel no siempre gana."),
    dict(v='c', tono='vivo', foto='cierre', p=0.20,
         t="Gana igual. Sólo que ahora *lo vemos correr*."),
    dict(v='l', tono='suave', foto='cierre', p=0.20,
         t="Contigo siempre aprendo algo, aunque venga a discutir."),
    dict(v='c', tono='suave', foto='cierre', p=0.25,
         t="Ven a discutir cuando quieras."),
    dict(v='c', tono='normal', foto='cierre', p=1.60,
         t="Y la pregunta que dejo abierta: ¿qué otro papel de la institución merecería el mismo seguimiento?"),
]
