# -*- coding: utf-8 -*-
"""Guion del vídeo del visor del Catastro, en formato podcast a dos voces.

Catalina lleva el hilo y estructura; Lorenzo pregunta, cuestiona y trae
analogías. La broma interna es que Lorenzo siempre acaba preguntando cuánto
pesan las cosas, y vuelve en el minuto tres.

CADA LATIDO ES UNA FRASE Y UN PLANO. Como la locución se sintetiza latido a
latido, la duración de cada frase se conoce exactamente, y el plano dura
exactamente lo que dura la frase que lo nombra. Ésa es toda la sincronía.

  v     voz: 'c' Catalina · 'l' Lorenzo
  t     texto
  foto  captura de capturas/
  z     encuadre: completo | mapa | panel | filtros | indicadores | cifra | cabecera
  rot   rótulo en pantalla (opcional)
  tono  normal | lento (cifras y remates) | vivo (reacciones) | suave (complicidad)
  p     pausa después, en segundos
"""

GUION = [
    # ---------------------------------------------------------------- apertura
    dict(v='c', tono='vivo',  foto='01_nacional', z='completo', p=0.20,
         t="Hoy abrimos un mapa que tiene un millón ochocientos veintisiete mil puntos."),
    dict(v='l', tono='vivo',  foto='01_nacional', z='mapa', p=0.15,
         t="¿Un millón ochocientos mil? ¿Y eso se abre en un navegador normal?"),
    dict(v='c', tono='normal', foto='01_nacional', z='mapa', p=0.15,
         t="Se abre. Y sin ningún servidor detrás, que es la parte que te va a gustar."),
    dict(v='l', tono='suave', foto='01_nacional', z='mapa', p=0.45,
         t="Ya me tienes."),
    dict(v='c', tono='normal', foto='01_nacional', z='cabecera', p=0.25,
         rot="Catastro de Usos de la Tierra y Recursos Vegetacionales · CONAF",
         t="Es el visor del Catastro de Usos de la Tierra y Recursos Vegetacionales, de CONAF."),
    dict(v='c', tono='lento', foto='01_nacional', z='cifra', p=0.30,
         rot="75,7 millones de hectáreas",
         t="Setenta y cinco coma siete millones de hectáreas. Todo el territorio catastrado."),
    dict(v='l', tono='normal', foto='01_nacional', z='completo', p=0.15,
         t="O sea que esto contesta de qué está hecho el país."),
    dict(v='c', tono='normal', foto='01_nacional', z='completo', p=0.65,
         t="Exacto. Y el matiz importa: no es una foto bonita, es el inventario."),

    # ------------------------------------------------------- qué es cada punto
    dict(v='l', tono='vivo',  foto='01_nacional', z='mapa', p=0.15,
         t="Antes de seguir, una duda de principiante. Cada punto, ¿es un árbol?"),
    dict(v='c', tono='vivo',  foto='01_nacional', z='mapa', p=0.30,
         t="No, y menos mal, porque serían bastantes más."),
    dict(v='c', tono='normal', foto='14_informacion', z='panel', p=0.20,
         rot="Cada punto es un centroide",
         t="Cada punto es el centroide de un polígono del Catastro."),
    dict(v='l', tono='normal', foto='14_informacion', z='panel', p=0.15,
         t="Centroide. El centro de gravedad de la mancha."),
    dict(v='c', tono='normal', foto='14_informacion', z='panel', p=0.35,
         t="Eso. No es una parcela ni un predio: es el polígono entero, representado por su centro."),
    dict(v='l', tono='vivo',  foto='14_informacion', z='panel', p=0.15,
         t="¿Y el tamaño del punto dice algo?"),
    dict(v='c', tono='normal', foto='14_informacion', z='panel', p=0.20,
         rot="El disco ocupa la superficie que declara",
         t="Dice la superficie que declara. Es un disco de la misma área que el polígono."),
    dict(v='c', tono='normal', foto='14_informacion', z='panel', p=0.20,
         t="Salvo donde no cabe. Ahí se recorta hasta tocar al vecino, sin invadirlo."),
    dict(v='l', tono='vivo',  foto='14_informacion', z='panel', p=0.15,
         t="Que pasará bastante, imagino."),
    dict(v='c', tono='lento', foto='14_informacion', z='panel', p=0.20,
         rot="Recortado en el 56 % de los puntos",
         t="En el cincuenta y seis por ciento de los puntos."),
    dict(v='l', tono='vivo',  foto='14_informacion', z='panel', p=0.25,
         t="Uf. Más de la mitad."),
    dict(v='c', tono='normal', foto='14_informacion', z='panel', p=0.70,
         t="Por eso la cifra exacta está siempre en la ficha, en los filtros y en las descargas. "
           "El mapa te orienta; no te mide."),

    # -------------------------------------------------------- las nueve clases
    dict(v='c', tono='normal', foto='02_clases', z='indicadores', p=0.20,
         rot="Nueve clases, y las nueve juntas son todo",
         t="El Catastro reparte el territorio entero en nueve clases."),
    dict(v='c', tono='normal', foto='02_clases', z='indicadores', p=0.25,
         t="La más grande son praderas y matorrales: veintinueve coma tres millones de hectáreas."),
    dict(v='c', tono='lento', foto='03_bosque', z='indicadores', p=0.20,
         rot="Bosques · 18,9 M ha · 24,9 %",
         t="Y bosques, dieciocho coma nueve millones. Un veinticinco por ciento del país."),
    dict(v='l', tono='normal', foto='15_solo_bosques', z='mapa', p=0.15,
         t="Un cuarto de Chile es bosque. Eso suena a titular."),
    dict(v='c', tono='vivo',  foto='15_solo_bosques', z='mapa', p=0.15,
         t="Suena. Y ahí está justo la trampa."),
    dict(v='l', tono='vivo',  foto='15_solo_bosques', z='mapa', p=0.20,
         t="Cuéntamela."),
    dict(v='c', tono='lento', foto='03_bosque', z='indicadores', p=0.25,
         rot="«Bosque» incluye las plantaciones",
         t="Que «bosque», en el Catastro, incluye las plantaciones."),
    dict(v='l', tono='normal', foto='03_bosque', z='indicadores', p=0.15,
         t="Ah. Entonces el pino radiata y el eucalipto entran en esa cifra."),
    dict(v='c', tono='normal', foto='03_bosque', z='indicadores', p=0.25,
         t="Entran. Por eso el visor lo desglosa: de esos dieciocho coma nueve millones, "
           "el ochenta y dos coma cuatro por ciento es bosque nativo."),
    dict(v='l', tono='suave', foto='03_bosque', z='indicadores', p=0.15,
         t="Me gusta que te lo diga él mismo, en vez de dejarte con el titular."),
    dict(v='c', tono='suave', foto='03_bosque', z='indicadores', p=0.65,
         t="Es la parte que más me gusta a mí también."),

    # --------------------------------------------------------------- filtrar
    dict(v='c', tono='normal', foto='01_nacional', z='filtros', p=0.15,
         rot="Dieciocho filtros temáticos",
         t="Y desde ahí puedes bajar todo lo que quieras. Hay dieciocho filtros."),
    dict(v='l', tono='vivo',  foto='01_nacional', z='filtros', p=0.15,
         t="Dieciocho. Dame el más bestia."),
    dict(v='c', tono='lento', foto='10_especie_modal', z='panel', p=0.20,
         rot="Especie · 989 clases",
         t="Especie. Novecientas ochenta y nueve."),
    dict(v='l', tono='vivo',  foto='10_especie_modal', z='panel', p=0.15,
         t="Novecientas ochenta y nueve especies distintas."),
    dict(v='c', tono='normal', foto='10_especie_modal', z='panel', p=0.30,
         t="Lenga, coihue, tepú, roble, pino insigne. Y no sólo árboles: toda la vegetación."),
    dict(v='c', tono='normal', foto='17_losrios_bosque', z='completo', p=0.15,
         t="Y se cruzan entre sí. El mapa y todas las cifras muestran sólo lo que pasa todos los filtros a la vez."),
    dict(v='l', tono='vivo',  foto='17_losrios_bosque', z='completo', p=0.20,
         t="Enséñame uno."),
    dict(v='c', tono='normal', foto='17_losrios_bosque', z='indicadores', p=0.20,
         rot="Los Ríos · sólo bosque · 54.263 polígonos",
         t="Los Ríos, sólo bosque. Un coma dos millones de hectáreas, cincuenta y cuatro mil polígonos."),
    dict(v='c', tono='lento', foto='17_losrios_bosque', z='indicadores', p=0.25,
         t="Ochenta coma siete por ciento nativo. Dieciocho coma cuatro, plantación."),
    dict(v='l', tono='suave', foto='19_sentinel', z='mapa', p=0.15,
         t="Y se ve. Se ve la forma del bosque valdiviano."),
    dict(v='c', tono='normal', foto='19_sentinel', z='mapa', p=0.70,
         rot="Fondo Sentinel-2",
         t="Con la imagen satelital de fondo, sí. Esto es Sentinel-2."),

    # ------------------------------------------------------- SNASPE y SIMEF
    dict(v='c', tono='normal', foto='07_snaspe', z='indicadores', p=0.15,
         t="Hay dos capas más que vale la pena mirar. La primera: qué hay dentro del SNASPE."),
    dict(v='l', tono='normal', foto='07_snaspe', z='indicadores', p=0.15,
         t="Las áreas protegidas del Estado."),
    dict(v='c', tono='lento', foto='07_snaspe', z='indicadores', p=0.35,
         rot="SNASPE · 90 unidades · 15,8 M ha",
         t="Noventa unidades. Quince coma ocho millones de hectáreas dentro."),
    dict(v='c', tono='normal', foto='08_simef', z='indicadores', p=0.15,
         t="Y la segunda, el cambio de bosque nativo, con datos del SIMEF."),
    dict(v='l', tono='vivo',  foto='08_simef', z='indicadores', p=0.15,
         t="¿Y qué dice?"),
    dict(v='c', tono='normal', foto='08_simef', z='indicadores', p=0.25,
         rot="36.919 ha → 9.983 ha",
         t="Que en el único par de períodos que son comparables entre sí, la pérdida bruta "
           "baja de treinta y seis mil novecientas diecinueve hectáreas a nueve mil novecientas ochenta y tres."),
    dict(v='l', tono='normal', foto='08_simef', z='indicadores', p=0.15,
         t="Baja muchísimo. ¿Eso es una buena noticia?"),
    dict(v='c', tono='lento', foto='08_simef', z='indicadores', p=0.70,
         t="Es una buena noticia con una nota al pie enorme."),

    # ------------------------------------------------ la advertencia central
    dict(v='c', tono='normal', foto='09_anios', z='indicadores', p=0.20,
         t="Y esa nota al pie es lo más importante de todo el visor."),
    dict(v='c', tono='lento', foto='09_anios', z='indicadores', p=0.25,
         rot="El Catastro no es una serie temporal",
         t="El Catastro no es una serie temporal."),
    dict(v='l', tono='vivo',  foto='09_anios', z='indicadores', p=0.15,
         t="Explícame eso, porque en un mapa nacional suena rarísimo."),
    dict(v='c', tono='normal', foto='09_anios', z='indicadores', p=0.20,
         t="Cada región se levantó en un año distinto. Entre dos mil catorce y dos mil veinticuatro."),
    dict(v='c', tono='normal', foto='09_anios', z='indicadores', p=0.15,
         t="Coquimbo es de dos mil catorce. Los Ríos, de dos mil veinticuatro."),
    dict(v='l', tono='lento', foto='09_anios', z='indicadores', p=0.20,
         t="Diez años de diferencia."),
    dict(v='c', tono='normal', foto='09_anios', z='indicadores', p=0.20,
         rot="Comparar regiones es comparar años distintos",
         t="Diez. Comparar dos regiones entre sí es comparar fotos de años distintos."),
    dict(v='l', tono='normal', foto='09_anios', z='indicadores', p=0.15,
         t="Y el visor lo advierte."),
    dict(v='c', tono='normal', foto='09_anios', z='indicadores', p=0.70,
         t="Lo dice tres veces, en tres sitios distintos. Está puesto a propósito."),

    # ------------------------------------------------------ cómo está hecho
    dict(v='l', tono='vivo',  foto='01_nacional', z='completo', p=0.15,
         t="Vale. Ahora sí, la pregunta de siempre: ¿cuánto pesa?"),
    dict(v='c', tono='suave', foto='01_nacional', z='completo', p=0.25,
         t="Sabía que ibas a preguntar eso."),
    dict(v='c', tono='lento', foto='01_nacional', z='completo', p=0.20,
         rot="49,4 MB · un binario columnar",
         t="Cuarenta y nueve coma cuatro megas. Un binario columnar que viaja entero al navegador."),
    dict(v='l', tono='vivo',  foto='01_nacional', z='completo', p=0.15,
         t="¿Sin backend? ¿Nada?"),
    dict(v='c', tono='normal', foto='01_nacional', z='completo', p=0.20,
         t="Nada. El sitio es estático, y eso es una decisión tomada, no una carencia."),
    dict(v='l', tono='normal', foto='16_araucania', z='mapa', p=0.15,
         t="Un millón ochocientos mil puntos dibujados en tu propio computador."),
    dict(v='c', tono='normal', foto='16_araucania', z='mapa', p=0.70,
         t="Con deck.gl sobre Leaflet. Y por eso mismo puedes filtrar sin esperar a nadie."),

    # ------------------------------------------------------------------ cierre
    dict(v='c', tono='normal', foto='12_descargar', z='panel', p=0.15,
         t="Dos cosas más y cerramos. Puedes descargar lo que estás viendo."),
    dict(v='l', tono='vivo',  foto='12_descargar', z='panel', p=0.15,
         t="¿Lo filtrado, o todo?"),
    dict(v='c', tono='normal', foto='13_compartir', z='panel', p=0.20,
         rot="El enlace guarda el ámbito, las clases y el mapa base",
         t="Lo filtrado. Y puedes compartir el enlace: guarda el ámbito, las clases activas y el mapa base."),
    dict(v='l', tono='normal', foto='13_compartir', z='panel', p=0.15,
         t="O sea que te mando una vista exacta y tú abres exactamente lo mismo."),
    dict(v='c', tono='suave', foto='13_compartir', z='panel', p=0.15,
         t="Exactamente lo mismo. Para mí es la mejor función que tiene."),
    dict(v='l', tono='suave', foto='13_compartir', z='panel', p=0.60,
         t="Es la más humana, en todo caso."),
    dict(v='c', tono='normal', foto='18_satelite', z='completo', p=0.20,
         t="Resumiendo: un inventario de todo el territorio, nueve clases, dieciocho filtros, "
           "novecientas ochenta y nueve especies."),
    dict(v='c', tono='normal', foto='18_satelite', z='completo', p=0.25,
         t="Y una advertencia honesta de que cada región es de un año distinto."),
    dict(v='l', tono='normal', foto='18_satelite', z='completo', p=0.40,
         t="Que es justo lo que separa un dato de una cifra suelta."),
    dict(v='c', tono='normal', foto='18_satelite', z='mapa', p=0.20,
         t="Y con eso les dejo una pregunta abierta. Cuando una región se vuelva a levantar…"),
    dict(v='c', tono='lento', foto='18_satelite', z='mapa', p=0.35,
         rot="¿Qué se podrá comparar de verdad?",
         t="…¿qué vamos a poder comparar de verdad, y qué no?"),
    dict(v='l', tono='suave', foto='18_satelite', z='mapa', p=0.20,
         t="Eso nos lo cuentas tú, supongo."),
    dict(v='c', tono='suave', foto='18_satelite', z='mapa', p=1.60,
         t="Te lo cuento yo."),
]
